// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xPeJFHU-5ZxaWssCzn8b4VKoXWuLQIg',
    appId: '1:951213639857:web:07165411e82e5f0f727a90',
    messagingSenderId: '951213639857',
    projectId: 'wildsnap-fb432',
    authDomain: 'wildsnap-fb432.firebaseapp.com',
    storageBucket: 'wildsnap-fb432.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavGvTLyUn7eWtx0BoY9bJAiGoURc_Wv0',
    appId: '1:951213639857:android:523e15646bcea7c9727a90',
    messagingSenderId: '951213639857',
    projectId: 'wildsnap-fb432',
    storageBucket: 'wildsnap-fb432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQNk9Y0jyZheMs3nag9bX7hAWoCNwBaQ',
    appId: '1:951213639857:ios:7edc39fcff642fe6727a90',
    messagingSenderId: '951213639857',
    projectId: 'wildsnap-fb432',
    storageBucket: 'wildsnap-fb432.firebasestorage.app',
    iosBundleId: 'fr.abbas.wildsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8xPeJFHU-5ZxaWssCzn8b4VKoXWuLQIg',
    appId: '1:951213639857:web:0e4b04902dd250f8727a90',
    messagingSenderId: '951213639857',
    projectId: 'wildsnap-fb432',
    authDomain: 'wildsnap-fb432.firebaseapp.com',
    storageBucket: 'wildsnap-fb432.firebasestorage.app',
  );
}
